planner:
  goal_tolerance: 0.2
  ctrl_pt_dist: 0.4
  planning_horizon: 5.0
  collision_weight_increase_factor: 2.0
  max_restart_num: 3
  global_interpoint_dist_thresh: 4.0
  replan_thresh: 1.5
  no_replan_thresh: 0.5
  swarm_clearance: 0.5
  swarm_replan_cooldown: 0.01
  swarm_priority_enabled: true
  safety_check_interval: 0.05
  safety_sample_dt: 0.01
  emergency_time: 1.0
  emergency_vel_threshold: 0.1
  emergency_stop_duration: 1.0
  pm_process_planning_interval: 0.05
  pm_process_idle_sleep_time: 0.01
  agent_process_control_interval: 0.01
  agent_process_idle_sleep_time: 0.005

bspline_optimizer:
  lambda_smooth: 1.0
  lambda_dist: 0.5
  lambda_feasibility: 0.1
  lambda_fitness: 1.0
  lambda_swarm: 0.5
  tol: 1.0e-5
  safe_dist: 0.5
  swarm_sample_divisor: 5

# grid_map:
#   resolution: 0.1
#   map_size: [100, 100, 30]
#   origin: [0.0, 0.0, 0.0]
#   obstacles:
#     - obs_start_index: [60, 70, 0]
#       obs_size: [20, 5, 5]
#     - obs_start_index: [60, 70, 25]
#       obs_size: [20, 5, 5]      
#     - obs_start_index: [60, 70, 5]
#       obs_size: [5, 5, 20]
#     - obs_start_index: [75, 70, 5]
#       obs_size: [5, 5, 20]
#     - obs_start_index: [44, 44, 0]
#       obs_size: [12, 12, 30]
#     - obs_start_index: [20, 70, 0]
#       obs_size: [10, 10, 30]
#     - obs_start_index: [80, 30, 0]
#       obs_size: [10, 10, 30]
#     - obs_start_index: [30, 15, 0]
#       obs_size: [10, 10, 30]

# grid_map:
#   resolution: 0.1
#   map_size: [100, 100, 30]
#   origin: [0.0, 0.0, 0.0]
#   obstacles:
#     - obs_start_index: [0, 0, 0]
#       obs_size: [1, 1, 1]


# grid_map:
#   resolution: 0.1
#   map_size: [100, 100, 30]
#   origin: [0.0, 0.0, 0.0]
#   obstacles:
#     - obs_start_index: [44, 44, 0]
#       obs_size: [12, 12, 30]

grid_map:
  resolution: 0.1
  map_size: [30, 35, 20]
  origin: [-1.5, -1.5, 0.0]
  obstacles:
    - obs_start_index: [11, 11, 0]
      obs_size: [8,7,15]
